/* Generated By:JavaCC: Do not edit this line. StandardTokenizerConstants.java */
package it.unibz.instasearch.indexing.tokenizers.standard;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StandardTokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHANUM = 1;
  /** RegularExpression Id. */
  int APOSTROPHE = 2;
  /** RegularExpression Id. */
  int ACRONYM = 3;
  /** RegularExpression Id. */
  int NUM = 4;
  /** RegularExpression Id. */
  int P = 5;
  /** RegularExpression Id. */
  int HAS_DIGIT = 6;
  /** RegularExpression Id. */
  int ALPHA = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int CJ = 9;
  /** RegularExpression Id. */
  int KOREAN = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int NOISE = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ALPHANUM>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<NUM>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<CJ>",
    "<KOREAN>",
    "<DIGIT>",
    "<NOISE>",
  };

}
